<?php

/**
 * @file
 *   Amazon Mechanical Turk integration module file.
 */


/**
 * Implements hook_help().
 */
function mt_task_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mt_task':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("This module enables <a href='@openturk'>Openturk.org</a> to process data from <a href='@amt'>Amazon Mechanical Turk</a>.", array('@openturk' => 'http://openturk.org', '@amt' => 'http://mturk.com')) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_mt_operations().
 * This hook is for mt_task to display a list of operations in a mt_task node.
 * The returned array follows the definition of hook_menu()
 */
function mt_task_mt_operations() {
  return array(
    'mt_task/%/get_balance()' => array(
      'title' => 'Get Balance',
      'description' => 'Retrieve the balance of your AMT Requester account. Please see results in the command list table below. Use this operation to test this application.',
    ),
    'mt_task/%/load_all_hits()' => array(
      'title' => 'Load All HITs',
      'description' => 'Load all HITs ever submitted to AMT from my account.',
    ),
    'mt_task/%/load_hits()' => array(
      'title' => 'Load HITs',
      'description' => 'Load HITs into this site. Please specify hit_type_id in "MT Properties". Otherwise your latest HIT_TYPE would be loaded.',
    ),
    'mt_task/%/load_assignments()' => array(
      'title' => 'Load Assignments',
      'description' => 'Load worker assignments for the HITs into the site. Please load HITs first. Run this command regularly to get updates from AMT.',
    ),
  );
}

/**
 * Implementation of hook_menu
 */
function mt_task_menu() {
  // 'title' and 'description' needs to be untranslated
  $operations = module_invoke_all('mt_operations');
  foreach ($operations as $path => &$operation) {
    if (!isset($operation['page callback'])) {
      $operation['page callback'] = 'mt_task_create_command';
    }
    if (!isset($operation['page arguments'])) {
      $operation['page arguments'] = array(0, 1, 2);
    }
    if (!isset($operation['access callback'])) {
      $operation['access callback'] = 'mt_task_access';
    }
    if (!isset($operation['access arguments'])) {
      $operation['access arguments'] = array(1);
    }  
    if (!isset($operation['type'])) {
      $operation['type'] = MENU_CALLBACK;
    }  
  }
  
  $items = array(
    'node/%/mt_operations' => array(
      'title' => 'Operations',
      'description' => 'Operations you can do with this AMT task',
      'page callback' => 'mt_task_display_operations',
      'page arguments' => array(1),
      'access callback' => 'mt_task_access',
      'access arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
    ),
  );
  return $items + $operations;
}


/**
 * Implements hook_node_info().
 */
function mt_task_node_info() {
  return array(
    'mt_task' => array(
      'name' => t('Mechanical Turk Task'),
      'base' => 'mt_task',
      'description' => t('Each <em>MT Task</em> node represent a task on Amazon Mechanical Turk.'),
    )
  );
}

/**
 * Implements hook_form().
 */
function mt_task_form($node, $form_state) {
  return node_content_form($node, $form_state);
}


/**
 * Implements hook_permission()
 */
function mt_task_permission() {
  $perms = array(
    'administer mt_task' => array(
      'title' => t('Administer Mechanical Turk tasks'),
      'description' => t('You need to have this permission in order to administer any mt_task nodes'),
    ),
  );
  return $perms;
}

function mt_task_access($task_id) {
  if(user_access('administer mt_task') != TRUE) {
    return FALSE;
  }
  $node = node_load($task_id);
  if (!node_access('create', $node) && !node_access('edit', $node)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implementation of hook_node_view
 */
/*function mt_task_node_view($node, $view_mode, $langcode) {
  global $user;
  # TODO: this seems redundant to node access permission. consider remove it.
  if ($node->uid != $user->uid || !user_access('administer mt_task')) {
    // if no permission, then do nothing.
    return;
  }
  
  // only for 'full' view.
  if ($node->type == 'mt_task' && $view_mode == 'full' 
      && node_is_page($node) && empty($node->in_preview) ) {

    // generate the "operations" section
    $operations_orig = module_invoke_all('mt_operations');
    $operations = array();
    $app_id_set = array();
    // replace wildcard in hook_menu to be the node_id.
    foreach ($operations_orig as $path => $operation) {
      $operations[strtr($path, array('%' => $node->nid))] = $operation;
      if ($app_id = strstr($path, '/', TRUE)) {
        $app_id_set[] = $app_id;
      }
    }
    $node->content['mt_task_operations'] = array(
      '#markup' => theme('async_command_operations', array('operations' => $operations, 'title' => t('Amazon Mechanical Turk Operations'))),
      '#weight' => 1,
    );

    // display recent commands with this task
    $recent_command = async_command_retrieve_command_list(array_unique($app_id_set), NULL, $node->nid);
    $node->content['mt_task_command_list'] = array(
      '#markup' => theme('async_command_list', array('command_list' => $recent_command, 'cols' => array('uid','command','created','changed','status','message'))),
      '#weight' => 2,
    );
  }
}*/


function mt_task_display_operations($task_id) {
  $node = node_load($task_id);
  // generate the "operations" section
  $operations_orig = module_invoke_all('mt_operations');
  $operations = array();
  $app_id_set = array();
  // replace wildcard in hook_menu to be the node_id.
  foreach ($operations_orig as $path => $operation) {
    $operations[strtr($path, array('%' => $node->nid))] = $operation;
    if ($app_id = strstr($path, '/', TRUE)) {
      $app_id_set[] = $app_id;
    }
  }  
  
  $content = theme('async_command_operations', array('operations' => $operations, 'title' => t('Amazon Mechanical Turk Operations')));
  // display recent commands with this task
  $recent_command = async_command_retrieve_command_list(array_unique($app_id_set), NULL, $node->nid);
  $content .= theme('async_command_list', array('command_list' => $recent_command, 'cols' => array('uid','command','created','changed','status','message')));
  return $content;
}



function mt_task_create_command($app, $task_id, $command) {
  async_command_create_command($app, $command, array('eid'=>$task_id));
  // note: @command will be check_plain() automatically.
  drupal_set_message(t('We have put your request @command in the queue. It will be executed soon. Please refresh the page to see the update.', array('@command' => $command)));
  drupal_goto("node/$task_id/mt_operations");
}


/**
 * Implements hook_cron().
 */
function mt_task_cron() {
  // by default, avoid duplicate
  async_command_create_command('mt_task', 'update_worker()', array('uid' => 0));
}


/**
 * Implements hook_user_view
 */
function mt_task_user_view($account, $view_mode, $langcode) {
  $worker_id = encset_ini_get($account->mt_properties_secure, 'worker_id', NULL);
  if ($view_mode == 'full' && $worker_id != NULL) {
    $account->content['summary']['mt_worker_id'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('AMT Worker ID'),
      //'#description' => t('The worker ID from AMT. Only workers need to input this in the MT Properties box.'),
      '#markup' => $worker_id,
      //'#weight' => -1,
    );
  }
}